### ISSUE TITLE
New Litter robot status: CSF

### ISSUE THREAD

**Issue by manutenfruits** [joshjcarrier/homeassistant-litter-robot#14]
I just got this error on my home assistant, I believe it might have been after upgrading to 0.104 but I can't say for sure (and looking at the implementation this is unlikely).

```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 419, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 284, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
    state = self.state
  File "/config/custom_components/litter_robot/sensor.py", line 82, in state
    return LITTER_ROBOT_UNIT_STATUS[unit_status]
KeyError: 'CSF'
```

I am trying to figure out what is causing this new state, the app just says "Cat Sensor Interrupted", but it's been a while and hasn't resumed cycling. I am also on vacation right now and don't have access to the device.

**Comment by joshjcarrier** [comment]
Cool I'll update for the new status and maybe better handle new surprise codes
