### ISSUE TITLE
message='Unauthorized

### ISSUE THREAD

**Issue by f3bandit** [joshjcarrier/homeassistant-litter-robot#33]
I've reset my password serveral times and factory reset the Litter robot as well. I know my username and password are correct.
idk maybe because im on android?

2020-08-04 20:35:15 ERROR (MainThread) [custom_components.litter_robot.litter_robot] [login] Unexpected exception: 401, message='Unauthorized', url='https://autopets.sso.iothings.site/oauth/token
2020-08-04 20:35:16 ERROR (MainThread) [custom_components.litter_robot.litter_robot] [update] Unexpected exception: 401, message='Unauthorized', url='https://autopets.sso.iothings.site/oauth/token
2020-08-04 20:35:17 ERROR (MainThread) [custom_components.litter_robot.litter_robot] [login] Unexpected exception: 401, message='Unauthorized', url='https://autopets.sso.iothings.site/oauth/token
2020-08-04 20:35:17 ERROR (MainThread) [custom_components.litter_robot] Error requesting litter_robot data: 401, message='Unauthorized', url='https://autopets.sso.iothings.site/oauth/token
2020-08-04 20:35:17 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up litter_robot platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 179, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/config/custom_components/litter_robot/sensor.py", line 38, in async_setup_platform
    for id in coordinator.data:
TypeError: 'NoneType' object is not iterable
2020-08-04 20:35:18 ERROR (MainThread) [homeassistant.helpers.script] Error executing script. Unexpected error for call_service at pos 1: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 193, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 382, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1281, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1316, in _execute_service
    await handler.func(service_call)
  File "/config/custom_components/litter_robot/__init__.py", line 89, in async_nightlight_on_handler
    await litter_robot.async_nightlight_on(call.data or list(litter_robot.robots.keys())[0])
IndexError: list index out of range
2020-08-04 20:35:18 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.140488570743296] list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 125, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1281, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1316, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 454, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 595, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 485, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/template/switch.py", line 202, in async_turn_on
    await self._on_script.async_run(context=self._context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 790, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 185, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 193, in _async_step
    await getattr(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 382, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1281, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1316, in _execute_service
    await handler.func(service_call)
  File "/config/custom_components/litter_robot/__init__.py", line 89, in async_nightlight_on_handler
    await litter_robot.async_nightlight_on(call.data or list(litter_robot.robots.keys())[0])
IndexError: list index out of range

**Comment by joshjcarrier** [comment]
Based on this mismatching line number `litter_robot/sensor.py", line 38` can you make sure you have the latest version of this integration running? I did momentarily mess up an auth case when I tried to reuse an existing login session.

**Comment by joshjcarrier** [comment]
Hmm I wonder what this is? Are you also running Android? And recently signed in with the latest version of the Litter-Robot app?

**Comment by jha-sudo** [comment]
I should have updated this. I had to manually reset the password to get it to work.

**Comment by hankmoody** [comment]
Hi
I'm running into the same problem. I have tried resetting my password and updating the custom component (using HACS). I'm running iOS app.

2020-08-30 13:55:50 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for litter_robot which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-08-30 13:55:58 ERROR (MainThread) [custom_components.litter_robot.litter_robot] [login] Unexpected exception: 401, message='Unauthorized', url='https://autopets.sso.iothings.site/oauth/token
2020-08-30 13:55:59 ERROR (MainThread) [custom_components.litter_robot.litter_robot] [update] Unexpected exception: 401, message='Unauthorized', url='https://autopets.sso.iothings.site/oauth/token
2020-08-30 13:56:02 ERROR (MainThread) [custom_components.litter_robot.litter_robot] [login] Unexpected exception: 401, message='Unauthorized', url='https://autopets.sso.iothings.site/oauth/token
2020-08-30 13:56:02 ERROR (MainThread) [custom_components.litter_robot] Error requesting litter_robot data: 401, message='Unauthorized', url='https://autopets.sso.iothings.site/oauth/token
2020-08-30 13:56:02 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up litter_robot platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 179, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/config/custom_components/litter_robot/sensor.py", line 38, in async_setup_platform
    for id in coordinator.data:
TypeError: 'NoneType' object is not iterable

**Comment by hankmoody** [comment]
Never mind, looks like the password didn't actually update when I tried directly from the app. Works fine after changing the password 👍
